#!/bin/bash
set -eo pipefail

verbose=0
usage="Usage: server-tool list-apps [-v]"
while [ $# -gt 0 ]; do
  case "$1" in
    -v|--verbose)
      verbose=1
      shift
      ;;
    *)
      echo "$usage"
      exit 1
      ;;
  esac
done

if [ "$verbose" -eq 1 ]; then
  list_server_tool_apps_verbose
else
  list_server_tool_apps
fi
